In [1]:
import numpy as np

array_one = np.array([1,2,3,4])

In [2]:
array_one

array([1, 2, 3, 4])

In [3]:
type(array_one)

numpy.ndarray

In [4]:
numbers=[9,8,7,6]

In [5]:
array_two=np.array(numbers)

array_two

array([9, 8, 7, 6])

In [6]:
array_of_zeros=np.zeros((3,4))

array_of_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])