In [1]:
import numpy as np

In [3]:
array_of_ones=np.ones((3,4))

array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
array_of_ones_int=np.ones((3,4), dtype=np.int16)

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [5]:
array_of_empty=np.empty((3,4))

array_of_empty

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
array_eye=np.eye(7)

array_eye

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [10]:
array_of_evens=np.arange(2,20,2)

array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
array_of_float=np.arange(1,5,0.2)

array_of_float

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [13]:
array_2d=np.array([(2,4,6),(3,5,7)])

array_2d

array([[2, 4, 6],
       [3, 5, 7]])

In [14]:
array_2d.shape

(2, 3)

In [15]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [16]:
array_nd=np.arange(8).reshape(2,4)

array_nd

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
array_nd=np.arange(8).reshape(4,2)

array_nd

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [18]:
a=np.arange(6)

a

array([0, 1, 2, 3, 4, 5])

In [20]:
a=np.arange(6)

print(a)

[0 1 2 3 4 5]
