In [1]:
import numpy as np

In [2]:
a = np.array([10,10,10])

b = np.array([5,5,5])

In [3]:
a+b

array([15, 15, 15])

In [4]:
a-b

array([5, 5, 5])

In [5]:
a/b

array([2., 2., 2.])

In [6]:
a%3

array([1, 1, 1], dtype=int32)

In [7]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])


print('A:\n',A)
print('B:\n',B)

A:
 [[1 1]
 [0 1]]
B:
 [[2 0]
 [3 4]]


In [8]:
A*B

array([[2, 0],
       [0, 4]])

In [9]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [10]:
ages = np.array([12,15,18,20])

In [11]:
ages.sum()

65

In [12]:
ages.max()

20

In [13]:
ages.min()

12

In [15]:
numbers = np.arange(12).reshape(3,4)

numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [17]:
numbers.sum(axis=1)

array([ 6, 22, 38])

In [21]:
test_scores = np.array([32.32,45.43,21.52,44.32,13.75])

print('mean test scores of the students: ')
print(np.mean(test_scores))

mean test scores of the students: 
31.468


In [22]:
print('median test scores of the students: ')
print(np.median(test_scores))

median test scores of the students: 
32.32
