In [1]:
import numpy as np

In [2]:
salaries=np.genfromtxt('salary.csv', delimiter=',')

In [3]:
salaries

array([60000., 58000., 56967., ..., 54647., 25000., 70000.])

In [4]:
salaries.shape

(1147,)

In [6]:
mean=np.mean(salaries)
median=np.median(salaries)
standard_deviation=np.std(salaries)
variance=np.var(salaries)

In [15]:
print('Mean=%i' %mean)
print('Median=%i' %median)
print('Standard Deviation=%i' %standard_deviation)
print('Variance=%i' %variance)

Mean=55894
Median=48000
Standard Deviation=55170
Variance=3043770333


In [16]:
a=np.arange(11)**2

In [17]:
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [18]:
a[2]

4

In [19]:
a[0:3]

array([0, 1, 4], dtype=int32)

In [20]:
a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [21]:
students=np.array([['poorni','parthi','yashita','shivani'],
                  [45,55,70,45],
                  [30,45,65,70]])

In [22]:
print(students)

[['poorni' 'parthi' 'yashita' 'shivani']
 ['45' '55' '70' '45']
 ['30' '45' '65' '70']]


In [23]:
students[0]

array(['poorni', 'parthi', 'yashita', 'shivani'], dtype='<U7')

In [24]:
students[1]

array(['45', '55', '70', '45'], dtype='<U7')

In [25]:
students[2]

array(['30', '45', '65', '70'], dtype='<U7')

In [26]:
students[0,1]

'parthi'